name: Deploy PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-preview:
    name: PR Preview 🔍
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      # Yarn install action
      - name: Run install
        uses: borales/actions-yarn@v5.0.0
        with:
          cmd: install

      # Yarn build action
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      # Generate commit hash action
      - name: Generate short commit hash
        run: git rev-parse --short HEAD > dist/commit_hash

      # Display the content of the commit hash file
      - name: Display commit hash file
        run: cat dist/commit_hash

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Preview URL

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 PR Preview has been deployed!
            
            Preview URL: https://ummitc.github.io/Links/pr-preview/pr-${{ github.event.pull_request.number }}/
            
            Changes will be automatically updated when you push new commits.
          edit-mode: replace 