name: CI/CD static site with Yarn
on: [push]
permissions:
  contents: write

jobs:
  build:
    name: Yarn deploy 🚀
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      # Yarn install action
      - name: Run install
        uses: borales/actions-yarn@v5.0.0
        with:
          cmd: install # will run `yarn install` command
      
      # Yarn build action
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # Generate commit hash action
      - name: Generate short commit hash
        run: git rev-parse --short HEAD > dist/commit_hash

      # Display the content of the commit hash file
      - name: Display commit hash file
        run: cat dist/commit_hash
      
      # Upload artifact action
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # Deploy action
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
